### ISSUE TITLE
Spaced repetition

### ISSUE THREAD

**Issue by jm42** [canicjusz/flashcards#1]
Learning from flashcards is excellent, thanks for making this project. Other flashcards apps, like Anki, use a [spaced repetition](https://en.wikipedia.org/wiki/Spaced_repetition) algorithm.

What do you think about implementing something like [this](https://github.com/joedel/spaced-repetition/blob/505e7b71d047d6b3d317a9890650e59cf08d09e8/spaced.js#L141)?

**Comment by canicjusz** [comment]
Thanks for taking interest in my project! 
I have been thinking about adding this feature in later updates but I stopped working on my KaiOS apps. In future I will rewrite the code and surely implement this.

**Comment by jm42** [comment]
This means is won't be implemented or that is already implemented?

I found [dolphinsr](https://github.com/yodaiken/dolphinsr) to be interesting as it uses (almost) the same algo than Anki.

**Comment by canicjusz** [comment]
Yes, this feature was implemented in today's update. You can download new versuon directly from this repo or by using BHackers store.

Algorythm in this app fkr calculating days till next repetition is very simple: Math.ceil(level*level*level*0.2)
"level" value starts from 0 and gets incremented every time you get the answer right and resets back to 0 when you answer wrong.
